version: '3'

services:
  pi:
    container_name: pi
    restart: always
    build: .
    volumes:
      - './:/app'
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
